source 'https://rubygems.org'

gem "jekyll", "~> 4.3.4" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

gem "just-the-docs", "0.10.1" # pinned to the current release
# gem "just-the-docs"        # always download the latest release

# Added to avoid current deprecation warnings
# https://github.com/just-the-docs/just-the-docs/issues/1541
gem "sass-embedded", "1.78.0"

# Added to avoid future deprecation warnings
gem "logger"
gem "csv"
gem "ostruct"
gem "base64"

# Added so the default layout is applied by default to all pages
gem "jekyll-default-layout"